mysql:
  image: mysql
  command: mysqld --skip-name-resolve
  env_file:
    - ./env/mysql.env
  expose:
   - "3306"

drupal:
  image: unblibraries/drupal:alpine-nginx-php7-8.x
  links:
    - mysql:mysql
  expose:
   - "80"
  ports:
    - "80:80"
  env_file:
    - ./env/drupal.env
