version: '2'

services:
  mysql:
    image: mysql
    command: mysqld --skip-name-resolve
    env_file:
      - ./env/mysql.env
    expose:
     - "3306"

  drupal:
    build: .
    links:
      - mysql:mysql
    expose:
     - "80"
    ports:
      - "80:80"
    env_file:
      - ./env/drupal.env
