mysql:
  image: mysql
  command: mysqld --skip-name-resolve
  environment:
    MYSQL_ROOT_PASSWORD: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
    MYSQL_DATABASE: drupal
  expose:
   - "3306"
drupal-EXTEND_SITESLUG:
  build: EXTEND_DEPLOY_BASENAME
  links:
    - mysql:mysql
  expose:
   - "80"
  ports:
    - "80:80"
  volumes:
    - EXTEND_DEPLOY_DIR/data:/app/html
  environment:
    DEPLOY_ENV: dev
    MYSQL_ROOT_PASSWORD: drupal
    DRUPAL_DB_PASSWORD: drupal
    DRUPAL_REVERT_FEATURES: 'TRUE'
